### ISSUE TITLE
Saving Image to camera setting?

### ISSUE THREAD

**Issue by dreyco676** [jim-easterbrook/python-gphoto2#10]
Hey I came across this:
http://gphoto-software.10949.n7.nabble.com/capture-image-and-save-on-camera-td14075.html

I'm wondering if there is a way via python to set this config? It might be helpful to include this on the example capture as well as I spent a decent amount of time trying to figure it out. 

gphoto2 --get-config capturetarget 
gphoto2 --set-config capturetarget=1

**Comment by jim-easterbrook** [comment]
The examples/camera-config-gui.py example allows you to get and set all your camera's config. The examples/get-camera-clock.py and examples/set-camera-clock.py examples show how to get and set one specific item (although it may appear under various names, just to make life a bit more complicated).

I don't think it's a good idea to have the capture example make config changes to the camera, but a couple of extra examples getting and setting the capture target wouldn't hurt.

**Comment by jim-easterbrook** [comment]
I've added a couple of examples in commit 5632fcc

**Comment by dreyco676** [comment]
Thanks thats super helpful!
