### ISSUE TITLE
Are the examples out of date?

### ISSUE THREAD

**Issue by jamoore5** [jim-easterbrook/python-gphoto2#101]
I pip installed the package and confirmed that I have version 2.2.1. However some of the examples do not work. 

For example,
```
$ python3 choose-camera.py
Traceback (most recent call last):
  File "choose-camera.py", line 79, in <module>
    sys.exit(main())
  File "choose-camera.py", line 35, in main
    camera_list = list(gp.Camera.autodetect())
AttributeError: type object 'gphoto2.camera.Camera' has no attribute 'autodetect'
```

**Comment by jim-easterbrook** [comment]
`gp.Camera.autodetect` has been added since version 2.2.1. Are you using the examples installed by pip or are you downloading the newer one from GitHub?
