### ISSUE TITLE
camera-config-gui-oo.py missing?

### ISSUE THREAD

**Issue by linuskohler** [jim-easterbrook/python-gphoto2#103]
Hello,

thank you very much for this library. I'm currently starting to play a little with it.

Unfortunately I can't find the file "camera-config-gui-oo.py" in the examples-folder that's needed for "examples/cam-conf-view-gui.py".
I also didn't manage to find it in older commits or versions. Did it get lost at some point?
If so could you please link it for me or add it to the examples again?

Thanks in advance.

**Comment by jim-easterbrook** [comment]
Sorry about that. I renamed it (dropping the -oo bit) but forgot it was used in the cam-conf-view-gui. (I didn't write the latter and haven't looked at it much.)
