### ISSUE TITLE
How to get date, not date value

### ISSUE THREAD

**Issue by kelerek** [jim-easterbrook/python-gphoto2#105]
Hi Jim,

datetime.get_value() retrieves some numbers and I don't know what it means. I want get date which is set on my camera.
How can i do it and how can I set new date?

**Comment by jim-easterbrook** [comment]
It's probably camera dependent. Possibly number of seconds since 1st Jan 1970, maybe something else. See Python's datetime module for some useful conversion routines.

The get-camera-clock.py and set-camera-clock.py examples show how to get and set the date/time.

**Comment by kelerek** [comment]
This is number of seconds since 1st Jan 1970. I counted it. Your examples are working on my Canon.
Thanks Jim <3
