### ISSUE TITLE
Libgphoto version problem

### ISSUE THREAD

**Issue by xdw-123** [jim-easterbrook/python-gphoto2#106]
This page is for reporting problems with the Python interface to libgphoto2. If your question is about using libgphoto2 you should ask on the [gphoto2 mailing list](http://gphoto.org/mailinglists/).

**Your system**
What version of Python are you using?
python3

What version of libgphoto2 have you installed?
ubantu16.04
libgphoto2.2.23
gphoto2.2.23

How have you installed (or attempted to install) python-gphoto2?
python setup.py build_swig
python setup.py build
sudo python setup.py install

**Your problem**
Hello author, I see that your libgphoto2 is updated to version 2.2.25, but I am using pip to install Gphoto version 2.5.9. How did you do it?When I call your example project, there will be no gPhoto2 module, so I use PIP3 install Gphoto.

**Comment by jim-easterbrook** [comment]
`libgphoto2` is usually installed from your operating system repository, so you don't have much choice of version. `python-gphoto2` is compiled for the installed version of `libgphoto2` when you use `pip` or `setup.py` to install it.

You currently have version 2.2.23 of `libgphoto2` and the `gphoto2` command line program, which is not far behind the latest version 2.2.25. The Python interface `python-gphoto2` is currently on version 2.2.2. Its version number is entirely separate from the `libgphoto2` version number.
