### ISSUE TITLE
serial number in  python-gphoto2?

### ISSUE THREAD

**Issue by Fred3D-tech** [jim-easterbrook/python-gphoto2#107]
I can't find a solution to add the serial number of my eos dslr to the listed devices...
I have several dslr connected to my jetson nano and I need to get the sn of the dslr to generate my filename.
Thanks

**Comment by jim-easterbrook** [comment]
With my Canon 100D the serial number is included in the `camera-summary.py` example output.

**Comment by jim-easterbrook** [comment]
It's also listed by the `camera-config-gui.py` example - it's the `eosserialnumber` or `serialnumber` config item.

**Comment by Fred3D-tech** [comment]
thanks... but is there a simple way (something like camera.get_serialnumber) to get the serial number like you get the port?

**Comment by jim-easterbrook** [comment]
Not that I'm aware of. The libgphoto2 documentation is here: http://www.gphoto.org/doc/api/

**Comment by Fred3D-tech** [comment]
thanks.. I went to this link before but for me this has nothing to do with a documentation. It is totally unusable.

**Comment by jim-easterbrook** [comment]
Click on `Files`, then `File List`, then `gphoto2` to get a list of header files, then click on the one whose documentation you want to read. It's a bit terse, but it's all there is. I'm sure the gphoto2 project would welcome improvements.
