### ISSUE TITLE
F-number options empty for Sony Cameras

### ISSUE THREAD

**Issue by henninghov** [jim-easterbrook/python-gphoto2#109]
This page is for reporting problems with the Python interface to libgphoto2. If your question is about using libgphoto2 you should ask on the [gphoto2 mailing list](http://gphoto.org/mailinglists/).

**Your system**
What version of Python are you using?
Python 3.7.3

What version of libgphoto2 have you installed?
gphoto2         2.5.26        
libgphoto2      2.5.26

How have you installed (or attempted to install) python-gphoto2?
Installed

**Your problem**
Please describe what you are trying to do and what goes wrong. A short Python script that shows the problem may be useful.

I have connected two different Sony cameras; Sony Alpha A9 and Sony Alpha A6000 and I am trying to get the f-number values that the cameras support. I am not getting any data now and the F-number options are empty.

I only get this when listing the data from : 

Label: F-Number
Readonly: 0
Type: RANGE
Current: 3.5
Bottom: 0
Top: 655.35
Step: 0.01
END

get-config /main/capturesettings/f-number

I am able to set the values but not extract all the possible options.

**Comment by jim-easterbrook** [comment]
The camera says the value can be anything from 0 to 655.35 in steps of 0.01. This is obviously absurd but that's not a problem with the Python interface.
