### ISSUE TITLE
Getting detected versions of python-gphoto2 and libgphoto2?

### ISSUE THREAD

**Issue by JoeWise** [jim-easterbrook/python-gphoto2#111]
Hello,

As a sanity check, I'd like to confirm which version of python-gphoto2 is installed along with which version of libgphoto2 is being utilized by python-gphoto2. Is this possible currently?

For comparison, using [gphoto2](https://github.com/gphoto/gphoto2) I can call `gphoto2 -v` on the command line to get something to similar to
> This version of gphoto2 is using the following software versions and options:
> gphoto2.......................2.5.23.1
> libgphoto2..................2.5.26
> libgphoto2_port........0.12.0
>

**Comment by jim-easterbrook** [comment]
The python-gphoto2 version is available as the constant `gp.__version__`. The libgphoto2 version is available with the command `gp.gp_library_version(verbose)`. `verbose` should be `0` or `1`.

**Comment by jim-easterbrook** [comment]
See also the `gphoto2_version.py` example program.

**Comment by JoeWise** [comment]
Awesome, that is exactly what I was looking for. Thank you!
