### ISSUE TITLE
nikon j3 in astroberry - gphoto2?

### ISSUE THREAD

**Issue by frits01** [jim-easterbrook/python-gphoto2#120]
I have a Nikon J3 camera, which I want to use as a DSLR in Astroberry (INDI/Ekos) for astrophotography. I only can make captures with the INDI-setting: Force BULB = off. But I can not define exposure times in Ekos because INDI Control Panel says: "Exposures shall utilize camera predefined exposure time before attempting BULB". Of course, I want to set up exposure settings in Ekos. Now it is not reacting on defined exposure times, it seems to be taking always captures with a predefined exposure time.
In Astroberry (Ekos), I made a setup with the selected device: Nikon DSLR. I understood that the driver is based on gphoto2. 
What can I do to solve this problem?

**Comment by jim-easterbrook** [comment]
This is the "issues" page for the Python interface to libgphoto2. Problems with "Astroberry (INDI/Ekos)" should be raised with whoever provides that. Problems with gphoto2 should be sent to one of the gphoto2 mailing lists.
