### ISSUE TITLE
Continuous shooting / burst

### ISSUE THREAD

**Issue by henningdekode** [jim-easterbrook/python-gphoto2#123]
Hey.

I am wondering if it is possible to start capture with continuous shooting and specifically with a start and stop function?
For example:
gp_camera_start_continuous_capture
and 
gp_camera_stop_continuous_capture

This to start and stop burst mode on the camera. With the former running until receiving a stop or the buffer is full.

or if there is another way to make create that within the library.

Thanks for a great library!

**Comment by jim-easterbrook** [comment]
You should ask on the gphoto2 mailing list. This "issues" page is for the Python interface to the libgphoto2 library, not the library itself.
