### ISSUE TITLE
EOS 6D call  gp_camera_wait_for_event make camera busy

### ISSUE THREAD

**Issue by SiuyuenChow** [jim-easterbrook/python-gphoto2#124]
Hi,
It's a great project

I have some questions to ask for help,

When polling for a new file, the camera has pressed the shutter to take a picture, the number of photos has not been added, nor has it received a return from GP_EVENT_FILE_ADDED. The camera seems to be busy all the time, and the camera model is EOS 6D

while (1) {
retval = gp_camera_wait_for_event (camera, 1, &evttype, &evtdata, context);
}

I noticed a pattern,

When I call gp_camera_wait_for_event once, the camera is fine
When I call gp_camera_wait_for_event the second time or later, the photo taken by the camera will never be written. It will always be like that
Student: I think what is blocking the camera from taking a picture and writing a picture
Is there something that needs to be released somewhere? gp_camera_wait_for_event

By the way, I'm not very familiar with C/C ++. As an iOS developer, I wish there were more comments in Examples

thanks
Siu

**Comment by jim-easterbrook** [comment]
This is the "issues" page for the **Python interface** to libgphoto2. Your question appears to be about using libgphoto2 from C. I suggest you ask on the gphoto2 mailing list.

**Comment by SiuyuenChow** [comment]
> This is the "issues" page for the **Python interface** to libgphoto2. Your question appears to be about using libgphoto2 from C. I suggest you ask on the gphoto2 mailing list.

Yes, that's right

However, GPhoto2 has not replied again, so I need to deal with it. I want to consult all sides, so that I can know more about it and think about possible solutions

**Comment by jim-easterbrook** [comment]
I do not know enough about how libgphoto2 works to answer your question.

**Comment by SiuyuenChow** [comment]
> I do not know enough about how libgphoto2 works to answer your question.

But it's all based on gphoto2, right?
So I want to look at gp_camera_wait_for_event/camera.wait_for_event
On call, what is fired that causes the camera to not write the photo?

**Comment by jim-easterbrook** [comment]
I do not know.

**Comment by SiuyuenChow** [comment]
> I do not know.

B: OK, thanks.
-- -- -
After calling gp_camera_wait_for_event, the photo can't be written to, which has been a problem for days.
Many ways have been tried and found to be fruitless.
-- -- -
Best wishes
Siu
