### ISSUE TITLE
咨询，libgphoto2能否运行在windows10系统上？？

### ISSUE THREAD

**Issue by chinaflys** [jim-easterbrook/python-gphoto2#132]
This page is for reporting problems with the Python interface to libgphoto2. If your question is about using libgphoto2 you should ask on the [gphoto2 mailing list](http://gphoto.org/mailinglists/).

**Your system**
What version of Python are you using?
我的电脑是windows10,pyton3.7
What version of libgphoto2 have you installed?
libgphoto2-2.5.24.tar.gz
How have you installed (or attempted to install) python-gphoto2?

**Your problem**
咨询，libgphoto2能否运行在windows10系统上？？

**Comment by jim-easterbrook** [comment]
libgphoto2 is not supported on Windows.
