### ISSUE TITLE
Command line alternative?

### ISSUE THREAD

**Issue by TheChymera** [jim-easterbrook/python-gphoto2#138]
Apologies for bothering your amazing Python package with this, just that I'm not sure where else I can inquire about this.

Is there any package which provides bash bindings (i.e. a command line interface)? I'm just looking to control the ISO of the camera, and the onboard controls don't work as soon as I connect it, so maybe I can do this from the computer.

I assume your package can also do this, but is there any way of doing this without maintaining an additional Python script?

**Comment by jim-easterbrook** [comment]
The gphoto2 project provides a command line program, called `gphoto2`.
http://www.gphoto.org/
