### ISSUE TITLE
Using remote control and tethering shooting (nearly) at the same time.

### ISSUE THREAD

**Issue by rafasgj** [jim-easterbrook/python-gphoto2#141]
**Your system**
Python 3.10.4
libgphoto2 2.5.29
python-gphoto 2.3.3

**Your problem**

I'm wrinting a GTK interface to shot from the computer that should allow to control the camera from the UI, but also allow tethering shooting by simply downloading files when shot through the camera.

The issue I'm having is that if I start waiting for events (to capture the image by triggering the camera button), when I try to capture  from the software, I get `[-110] I/O in progress`. Even after I stop the event thread, the camera is in a state that it seems to be always doing some I/O, and I can't control the camera from the UI anymore (if I restart the event thread, tethering shooting is still possible).

My question is, is it possible, using python-gphoto2, to swap between tethering shooting and remote control?

**Comment by jim-easterbrook** [comment]
I've no idea. If you can do it using C then you should be able to do it using Python.

**Comment by rafasgj** [comment]
I never tried using C (I'm too old for that ;-) ).

Do you know how can I debug it to see what's going on? (I've never debugged libgphoto2 before.)

**Comment by jim-easterbrook** [comment]
If you're using Python logging (`gp.use_python_logging()` function) then you can increase the verbosity by setting the Python logger to report `DEBUG` or `INFO` messages.

I suspect what you want to do may not be possible though. Once cameras switch over to "computer mode" it's probably difficult to switch back.
