### ISSUE TITLE
delete a file

### ISSUE THREAD

**Issue by rawexp** [jim-easterbrook/python-gphoto2#150]
I have my camera set to record RAW + JPG. I would like to retrieve the JPG and then delete it from the SD card.

I can achieve this through gphoto2 using a command such as: "gphoto2 -d /store_00020001/DCIM/100EOS1D/VQ4A4383.JPG"

Is there an equivalent function here? For example, something that would work like: gp.gp_file_delete('/store_00020001/DCIM/100EOS1D/VQ4A4383.JPG')

**Comment by jim-easterbrook** [comment]
The function's called `gp_camera_file_delete`, as documented here: http://www.gphoto.org/doc/api/gphoto2-camera_8h.html

The `clear-space.py` shows an example of its use.

**Comment by rawexp** [comment]
wonderful, thanks for the quick response
