### ISSUE TITLE
LGPL vs. GPL license?

### ISSUE THREAD

**Issue by erdmann** [jim-easterbrook/python-gphoto2#160]
Thanks very much for writing python-gphoto2!

I'd like to make use of it (but not extend it) in an MIT-licensed codebase, but I see that while libgphoto2 is [LGPL-licensed](https://github.com/gphoto/libgphoto2/blob/master/COPYING), your Python bindings are licensed under the GPL.  Would you please consider changing the license to LGPL to harmonize it with the libgphoto2 license?

**Comment by jim-easterbrook** [comment]
Does making python-gphoto2 a separately installed dependency of your MIT licensed stuff meet your requirements?

I can't remember why I chose GPL over LGPL. I think it was to prevent use in commercial software.

**Comment by erdmann** [comment]
My understanding is that if some code requires a GPL-licensed library to function, regardless of whether it's linked in a compiled language or imported in a dynamic language, it is obligated to be under the GPL itself.  

The main difference between the LGPL and the GPL is that LGPL requires that, like the GPL, modifications of the library itself are (L)GPL licensed, but that merely importing an LGPL-licensed module doesn't require the importer to then also  put their code under the GPL.

**Comment by jim-easterbrook** [comment]
A am not a lawyer so can't argue about linking vs importing, but it makes sense for python-gphoto2 to be under the same licence as libgphoto2.

I'll change the licence for the next release.

**Comment by erdmann** [comment]
Thank you very much!  This will save a huge amount of time.  What is your typical release schedule?

**Comment by jim-easterbrook** [comment]
I'm not that organised! Generally when I've made a significant change or there's a new release of libgphoto2 to include. I'm currently working on some unit tests for the Python package, which are failing on the GitHub Actions MacOS runner.

Expect a new release in weeks rather than months.

**Comment by erdmann** [comment]
Excellent.  Many thanks again!

**Comment by jim-easterbrook** [comment]
I think this may have influenced my original licence choice.
https://www.gnu.org/licenses/why-not-lgpl.html

**Comment by jim-easterbrook** [comment]
I've just released version 2.4.0 under LGPL.

**Comment by yuyou** [comment]
@jim-easterbrook 

Thanks for the changes. It seems, however,  that the license terms in the source code has not been updated from GPL to LGPL?
