### ISSUE TITLE
Test Virtual Camera

### ISSUE THREAD

**Issue by mgrl** [jim-easterbrook/python-gphoto2#161]
**Your system**
What version of Python are you using?

Actions Runner

What version of libgphoto2 have you installed?

2.5.30

**Your problem**

Hi, 
is the virtual camera testing supposed to work actually?
I try to use it in my actions and see that it seems not to work in yours also:
https://github.com/jim-easterbrook/python-gphoto2/actions/runs/5973932068/job/16207362107
Tests are skipped.

One reason could be because compared greater instead of greater or equal?
https://github.com/jim-easterbrook/python-gphoto2/blob/main/tests/vcamera.py#L43

Even if I change that and provide a path with images it does not detect a camera in my tests:
https://github.com/mgrl/photobooth-app/actions/runs/5986350130/job/16239387306#step:8:779

You have an idea why this is happening or is it still experimental?

**Comment by jim-easterbrook** [comment]
I can't get the virtual camera working in libgphoto2 v2.5.30, I think because of this bug: https://github.com/gphoto/libgphoto2/issues/842

It works with libgphoto2 from GitHub, so I assume will work with the next release of libgphoto2.

**Comment by mgrl** [comment]
Hm, okay, thanks! Will keep watching this issue.

**Comment by jim-easterbrook** [comment]
I've just released v2.5.0 which includes libgphoto2 v2.5.31 in its "binary wheels".

**Comment by mgrl** [comment]
Awesome, works! Thank you very much!
