### ISSUE TITLE
Cannot install on Mac

### ISSUE THREAD

**Issue by WillNye** [jim-easterbrook/python-gphoto2#17]
Awesome package, I've been using it for a couple months on Ubuntu. Unfortunately, I can't seem to get it working on Mac. I've tried

sudo pip install -V gphoto2

building from swig

and building from the tar

All fail with the same error:

Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    universal_newlines=True).split('.')[:2])
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I'm not sure what is causing this as I do have gphoto2 installed:
$ gphoto2
Usage: gphoto2 [-?qvalLnPTDR] [-?|--help] [--usage] [--debug]....

Any help would be awesome!

**Comment by jim-easterbrook** [comment]
I think the `pkg-config` command is missing. (I've assumed this is present on any system capable of compiling software - obviously I shouldn't.)

**Comment by DannyBoyBroadSword** [comment]
Easily Fixed by Installing `pkg-config` with Homebrew
`brew install pkg-config` NO ROOT.

**Comment by seeme00** [comment]
Hi.
I get something similar on windows with python 3.5

>  Traceback (most recent call last):
>   File "E:\Python35-32\lib\runpy.py", line 174, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "E:\Python35-32\lib\runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "E:\Projects\gphoto2\setup.py", line 35, in <module>
>     universal_newlines=True).split('.')[:2])
>   File "E:\Python35-32\lib\subprocess.py", line 626, in check_output
>     **kwargs).stdout
>   File "E:\Python35-32\lib\subprocess.py", line 693, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "E:\Python35-32\lib\subprocess.py", line 947, in __init__
>     restore_signals, start_new_session)
>   File "E:\Python35-32\lib\subprocess.py", line 1224, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

Thanks.

**Comment by jim-easterbrook** [comment]
Have you installed pkg-config?

**Comment by seeme00** [comment]
Tried on a raspberry pi (jessi,  python 2.7).
sudo aptitude install pkg-config
pip install --upgrade pip
pip install --upgrade setuptools
pip install gphoto2 ->same error.

Will try with brew later.

**Comment by jim-easterbrook** [comment]
I usually use apt-get to install packages on a Pi. I doubt it's exactly the same error as pkg-config is now installed. I suspect it's now the development headers of libgphoto2 (or Python) that are missing.

**Comment by seeme00** [comment]
Finally getting somewhere. You were right about missing libs. Thanks a lot!
