### ISSUE TITLE
error -105 GP_ERROR_MODEL_NOT_FOUND

### ISSUE THREAD

**Issue by andrewyguo** [jim-easterbrook/python-gphoto2#181]
I am trying to use python-gphoto2 with my Sony A7M4 and I was getting the same errors as [this issue.](https://github.com/jim-easterbrook/python-gphoto2/issues/175) 

I followed the advice and installed `libgphoto2`. I didn't comment out anything since I think there has already been a fix merged in. Please correct me if I am wrong. 

**Your system**
`Python 3.9.0`

`Ubuntu 22.04.5 LTS`

What version of libgphoto2 have you installed?
```
$ pkg-config --modversion libgphoto2
2.5.31.1
```
How have you installed (or attempted to install) python-gphoto2?

Yes. I have installed following instructions here: 
https://github.com/jim-easterbrook/python-gphoto2/blob/main/INSTALL.rst#local-libgphoto2 

**Your problem**
However, I am now getting this error with my A7M4: 

```
import gphoto2 as gp

error, camera = gp.gp_camera_new()


print("error after gp_camera_new: ", error)

error = gp.gp_camera_init(camera)
print("error after gp_camera_init: ", error)
```
Output: 
```
error after gp_camera_new:  0
error after gp_camera_init:  -105
```
Which corresponds to `GP_ERROR_MODEL_NOT_FOUND`. 

I was not getting this before. It was able to initialize the camera fine.

**Comment by jim-easterbrook** [comment]
Check the output of `python -m gphoto2` to see which version of libgphoto2 you are using.

**Comment by andrewyguo** [comment]
```
$ python -m gphoto2
python-gphoto2 version: 2.5.1
libgphoto2 version: 2.5.31.1, standard camlibs (SKIPPING docupen lumix), gcc, no ltdl, no EXIF
libgphoto2_port version: 0.12.2, iolibs: disk ptpip serial, gcc, no ltdl, no EXIF, no USB, serial without locking
python-gphoto2 examples: /home/ykguo/.local/lib/python3.9/site-packages/gphoto2/examples
```

**Comment by jim-easterbrook** [comment]
That shows it's using your local libgphoto2. You could try building an earlier version (that you know worked) and using that with python-gphoto2.

I don't think you have a python-gphoto2 bug though.

**Comment by andrewyguo** [comment]
Thanks, let me see if I can revert to an older version of `libgphoto2`. I am curious how @ertdfgcvb was able to fix the issue earlier. Seems like they were also using v2.5.31 of `libgphoto2`

**Comment by jim-easterbrook** [comment]
-105 is also the error you get if there's no camera connected (e.g. if it's gone to sleep). Worth checking - I know how easy it can be to overlook the obvious.

**Comment by andrewyguo** [comment]
@jim-easterbrook, 

I made sure the camera is connected and awake. I have downgraded libgphoto to be v2.5.29. This is my gphoto version now: 

```
$ python -m gphoto2
python-gphoto2 version: 2.5.1
libgphoto2 version: 2.5.29, standard camlibs (SKIPPING docupen lumix), gcc, no ltdl, no EXIF
libgphoto2_port version: 0.12.0, iolibs: disk ptpip serial, gcc, no ltdl, no EXIF, no USB, serial without locking
```

I noticed it says no USB. Is this a problem?

**Comment by andrewyguo** [comment]
Another thing to note, I re-installed `gphoto2` using the binary wheel: 

```
$ pip3 install gphoto2 --user --only-binary :all:
$ $ python -m gphoto2
python-gphoto2 version: 2.5.1
libgphoto2 version: 2.5.31, standard camlibs, gcc, no ltdl, EXIF
libgphoto2_port version: 0.12.2, iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi vusb, gcc, no ltdl, EXIF, USB, serial without locking

```

But I am getting a new error: 

```
$ python examples/camera-summary.py 
Traceback (most recent call last):
  File "/home/ykguo/camera/python-gphoto2/examples/camera-summary.py", line 51, in <module>
    sys.exit(main())
  File "/home/ykguo/camera/python-gphoto2/examples/camera-summary.py", line 37, in main
    camera.init()
gphoto2.GPhoto2Error: [-7] I/O problem
```

**Comment by andrewyguo** [comment]
I was thinking the same. Thanks for your help. I will look in the `gphoto2` repository

**Comment by andrewyguo** [comment]
for those who encounter a similar issue, the root of my issue was this: 

https://github.com/gphoto/gphoto2/issues/655
