### ISSUE TITLE
Unable to get libgphoto2-2.5.9 

### ISSUE THREAD

**Issue by benoitguigal** [jim-easterbrook/python-gphoto2#19]
This error happened last time I run the script

**Comment by jim-easterbrook** [comment]
What script?

**Comment by benoitguigal** [comment]
I am so sorry I swapped tabs in my browser, this is not relevant to this repository

**Comment by jim-easterbrook** [comment]
No problem. I'm glad I'm not the only one who makes mistakes like that.
