### ISSUE TITLE
capture-image and get-files not working

### ISSUE THREAD

**Issue by chrisimars** [jim-easterbrook/python-gphoto2#24]
Hi Jim, I am working with python-gphoto2 on a Raspberry Pi with a Nikon D7200 camera.
I can perform all functions I have tried ok but having trouble getting files from camera.
Neither the capture-image or get-files works.  The camera SD-card access LED goes on but the program exits when it gets to the 
Camera_file = gp.check_result(gp.gp_camera_file_get(
            camera, file_path.folder, file_path.name,
            gp.GP_FILE_TYPE_NORMAL, context))
line.  I then have to turn camera off and back on to talk to it again.
I can get files and capture images from gphoto2, v2.5.10 with libgphoto2 2.5.4.
Any ideas?
Thanks,
Chris

**Comment by jim-easterbrook** [comment]
Any error messages or other console output at all?

**Comment by chrisimars** [comment]
Jim, no the python program just quits.  I have tried debugging via IDLE3 but it will not step into the call.
Chris


Chris Marshall | Hardware & Software Engineering | Event Imaging Solutions
Kodak Alaris Imaging | 2400 Mt Read Blvd | MC 03013 | Rochester, NY 14615-3013
chris.marshall@kodakalaris.com | (585) 230-0782
[cid:image002.png@01D20F61.6C38ECC0]

     The information contained in this e-mail is confidential. It is intended only for the use of the named recipient(s).
    If you have received this e-mail in error, please immediately inform the sender and delete the message.
    If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution,
    or copying of this communication is strictly prohibited.

**Comment by jim-easterbrook** [comment]
That's odd. I suspect you are getting a segfault or similar, although they're not usually silent. I assume you've called `gp.use_python_logging()` at the start of your program (and set up `logging.basicConfig()`) as in the python-gphoto2 example programs.

**Comment by chrisimars** [comment]
I have tried the example programs but I am not familiar with the logging, where do the messages go?


Chris Marshall | Hardware & Software Engineering | Event Imaging Solutions
Kodak Alaris Imaging | 2400 Mt Read Blvd | MC 03013 | Rochester, NY 14615-3013
chris.marshall@kodakalaris.com | (585) 230-0782
[cid:image002.png@01D20F68.538E5D20]

     The information contained in this e-mail is confidential. It is intended only for the use of the named recipient(s).
    If you have received this e-mail in error, please immediately inform the sender and delete the message.
    If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution,
    or copying of this communication is strictly prohibited.

**Comment by jim-easterbrook** [comment]
You should get messages on the terminal where you run the program. It's best to use the command line for this sort of thing, rather than running in any sort of IDE.

**Comment by chrisimars** [comment]
Jim, ok let me try that and see if I get any messages that help.
Thanks,
Chris


Chris Marshall | Hardware & Software Engineering | Event Imaging Solutions
Kodak Alaris Imaging | 2400 Mt Read Blvd | MC 03013 | Rochester, NY 14615-3013
chris.marshall@kodakalaris.com | (585) 230-0782
[cid:image002.png@01D20F6A.19538660]

     The information contained in this e-mail is confidential. It is intended only for the use of the named recipient(s).
    If you have received this e-mail in error, please immediately inform the sender and delete the message.
    If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution,
    or copying of this communication is strictly prohibited.

**Comment by chrisimars** [comment]
Jim, whenever I try to run a program with the error logging I get the following message:
WARNING: gphoto2: (gp_port_set_error [gphoto2-port.c:1186]) The supplied vendor or product id (0x0,0x0) is not valid.
Not sure if that is related, I get this for functions that work in other programs without the logging.
Chris


Chris Marshall | Hardware & Software Engineering | Event Imaging Solutions
Kodak Alaris Imaging | 2400 Mt Read Blvd | MC 03013 | Rochester, NY 14615-3013
chris.marshall@kodakalaris.com | (585) 230-0782
[cid:image002.png@01D20F71.01E48400]

     The information contained in this e-mail is confidential. It is intended only for the use of the named recipient(s).
    If you have received this e-mail in error, please immediately inform the sender and delete the message.
    If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution,
    or copying of this communication is strictly prohibited.

**Comment by jim-easterbrook** [comment]
libgphoto2 seems to produce a lot of messages that aren't really a problem. It's not easy to tell which ones matter and which don't. I take it you're still not getting anything useful from your program that exits abruptly.
Can you try it on a different model of computer? (E.g. desktop Linux box instead of Raspberry Pi.)

**Comment by chrisimars** [comment]
Jim, not easily.  I am now focusing on just getting a file from the camera.  When you try to get the image the camera led for the storage card is on until you power cycle the camera.  Maybe the lower level code is not handling the data transfer properly.

On the capture side, I found out that the Nikon camera I am using only allows you to get the image from a still capture if the image is stored in SDRAM.  It sends events in that case with the imagebuffer as a parameter.  How does python-gphoto2 handle events?  Is that just in the libgphoto2 stuff?

Sorry to bother you with this but I am new to the gphoto2 stuff and want to get a camera working. I may try a Canon camera also.
Thanks,
Chris


Chris Marshall | Hardware & Software Engineering | Event Imaging Solutions
Kodak Alaris Imaging | 2400 Mt Read Blvd | MC 03013 | Rochester, NY 14615-3013
chris.marshall@kodakalaris.com | (585) 230-0782
[cid:image001.png@01D2100D.B980A200]

     The information contained in this e-mail is confidential. It is intended only for the use of the named recipient(s).
    If you have received this e-mail in error, please immediately inform the sender and delete the message.
    If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution,
    or copying of this communication is strictly prohibited.

**Comment by jim-easterbrook** [comment]
As far as I know the only libgphoto2 event handling (at the user program level) is `gp_camera_wait_for_event()`, which python-gphoto2 should handle OK.
