### ISSUE TITLE
gp_camera_wait_for_event ignores timeout, blocks for a long time

### ISSUE THREAD

**Issue by Ruuttu** [jim-easterbrook/python-gphoto2#29]
With the Canon EOS 600D, I'm polling gp_camera_wait_for_event in an endless loop with a timeout of 1 (ms). After physically triggering a shot on the camera, the function produces a GP_EVENT_FILE_ADDED event, but not before blocking for about 1.2 seconds. The duration is reduced when taking smaller pictures, so this might be the time it takes to download the image.

My goal is to download images in small chunks while keeping the loop interactive. Seems like this should be doable.

**Comment by jim-easterbrook** [comment]
Do you get the same behaviour with a C program? I'm not aware of anything in the Python interface that would add a delay, so your problem may be with libgphoto2 itself.

I don't think the image is being downloaded during your 1.2 second delay, I think the camera is busy saving it to its SD card (and so not responding to USB). If you don't want to store the image on the SD card you could try capturing to memory instead. (It might also be worth trying a faster SD card.)

**Comment by mangodan2003** [comment]
I'm also using a Canon EOS 600D and seeing unexpected behaviour trying to use gp_camera_wait_for_event.

It seems to just return right away. i.e. it never waits!

Python 3.4.5 (default, Feb 21 2017, 16:14:02) 
[GCC 4.9.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gphoto2 as gp
>>> context = gp.Context()
>>> camera = gp.Camera()
>>> camera.wait_for_event(1000,context)
[0, None]
>>> gp.gp_camera_wait_for_event(camera,1000,context)
[0, 0, None]
>>> gp.version.gp_library_version(1)
['2.5.14', 'all camlibs', 'gcc (C compiler used)', 'ltdl (for portable loading of camlibs)', 'EXIF (for special handling of EXIF files)']

Any pointers?

**Comment by jim-easterbrook** [comment]
How soon is "right away"? You're specifying a timeout of only 1 second.

**Comment by mangodan2003** [comment]
I realise that - right away is right away - i.e. much less than  1sec. fwiw specifying much longer makes no difference.

**Comment by jim-easterbrook** [comment]
I don't know then. The return value of 0 is `GP_EVENT_UNKNOWN` - the documentation says "unknown and unhandled event. argument is a char* or NULL" so maybe there's a string there that the Python interface is currently ignoring.
It would appear that you need to poll camera.wait_for_event in a loop until you get an event of interest. It might be worth asking for clarification on the libgphoto mailing list though.

**Comment by mangodan2003** [comment]
ok thanks, I remember finding that 0 meant gp.GP_EVENT_UNKNOWN come to think of it and wondered similar..

**Comment by mangodan2003** [comment]
>>> while True:
...  foo = camera.wait_for_event(10000,context)
...  if foo[0] != 0:
...    print(foo)
...    break
... 
[2, <Swig Object of type 'CameraFilePath *' at 0x767ac7c0>]

:)

**Comment by jim-easterbrook** [comment]
I've just added code to handle any string when `GP_EVENT_UNKNOWN` is returned. Trying it on my EOS 100D I get the following
```
Type "help", "copyright", "credits" or "license" for more information.
>>> import gphoto2 as gp
>>> ctx = gp.Context()
>>> cam = gp.Camera()
>>> cam.init(ctx)
>>> cam.wait_for_event(1000, ctx)
[0, 'PTP Property d105 changed']
>>> cam.wait_for_event(1000, ctx)
[0, 'PTP Property d108 changed']
>>> cam.wait_for_event(1000, ctx)
[0, 'PTP Property d106 changed']
>>> cam.wait_for_event(1000, ctx)
[0, 'PTP Property d107 changed']
>>> cam.wait_for_event(1000, ctx)
[0, 'PTP Property d109 changed']
>>> cam.wait_for_event(1000, ctx)
[0, 'PTP Property d10a changed']
>>> cam.wait_for_event(1000, ctx)
[0, 'PTP Property d10b changed']
>>> cam.wait_for_event(1000, ctx)
[0, 'PTP Property d10c changed']
>>>
```
I suspect I might run out of such events eventually.
