### ISSUE TITLE
Bug present in dev packages but OK in non-dev

### ISSUE THREAD

**Issue by supermikeedwards** [jim-easterbrook/python-gphoto2#34]
Hi,
I'm trying to use libgphoto2 to control my Canon 1300d from python. When I update all packages using gphoto2-updater (and choosing "latest dev version") I get a 2.5.14 version of libgphoto2. I can call the camera and take several shots from the terminal, but when I try and use libgphoto2 in python, I get "no module name".
On the other hand, when I install libgphoto2-dev as suggested on issue #1 , I get 2.5.4 version installed. I don't get an error from python with that version, but I do get the error known with latest Canon cameras : after 1 photo taken the connection with the camera is somehow lost and I get the "no memory" error message. 
Is this a known bug ? If it's just me, what can I do to solve this problem ?
Thanks in advance,
Mike

**Comment by jim-easterbrook** [comment]
Did you install python-gphoto2 after libgphoto2? The python extension is compiled and linked with libgphoto2 when you install it, so it may not work after installing a different version (or the same version in a different place).

**Comment by supermikeedwards** [comment]
Hi,
Thanks for the quick reply. I'm pretty sure I did, but then again I have some doubts as I have been trying to get it to work so much that I have been installing/updating very frequently. Do you have a recommendation of command to run to remove all elements, or do you just recomment to try to reinstall over current elements ? 
I used this : https://github.com/gonzalo/gphoto2-updater to update to latest versions
Thanks,
Mike

**Comment by jim-easterbrook** [comment]
I'm not a frequent Ubuntu user, and rarely install from source on any system unless the library I want is not in the system repository. In your first message you say you get "no module name". I don't recognise this error message so have no idea what's failing.

After installing the latest libgphoto2 with that script does `pkg-config --modversion libgphoto2` return the correct version? Does `pkg-config --cflags --libs libgphoto2` show the correct location? If so, then reinstalling python-gphoto2 (with `sudo pip install --force-reinstall -U gphoto2`) should link to the correct version.

**Comment by supermikeedwards** [comment]
Hi, 
Brilliant, that worked great thanks ! 
Mike
