### ISSUE TITLE
Examples not up-to-date

### ISSUE THREAD

**Issue by bensonz** [jim-easterbrook/python-gphoto2#39]
It seems a lot of functions now require context but none was used in examples (Specifically, the ones I looked at, choose-camera and capture).

For example, gp.Camera().init() needs a camera context and 

When I try to use the example an error would occur.

**Comment by jim-easterbrook** [comment]
The examples should be correct for the version of python-gphoto2 they are supplied with. Since version 1.8.0 context is optional for most functions. If you are using an older version you need the examples that were installed with that version. (Context can be `None` with the older versions.)
