### ISSUE TITLE
gp_camera_get_storageinfo[1][0].freeimages returns 0

### ISSUE THREAD

**Issue by ELI7VH** [jim-easterbrook/python-gphoto2#42]
some functions don't seem to be working on my 5d3

at the top of the camera, it says "831" but the method returns 0

**Comment by jim-easterbrook** [comment]
What result do you get with the `gphoto2` command line utility?
Does the clear-space.py example (run with no argument) report the right amount of space?
Have you checked the `fields` attribute to ensure the `freeimages` attribute is valid?
PS This is not a bug in python-gphoto2. Questions about using libgphoto2 should be asked on the gphoto2 mailing list.

**Comment by AkshayDeshmukh-Edmodo** [comment]
I think when first card is not in place, it returns zero.

**Comment by AkshayDeshmukh-Edmodo** [comment]
Py has fixed this issue but on Cpp library when first card is not in place, it shows this error. Any solution you found on this @ELI7VH  by chance?
