### ISSUE TITLE
Change from qt4 to qt5

### ISSUE THREAD

**Issue by TheOtherNeo** [jim-easterbrook/python-gphoto2#45]
Probably not that important, but when setting up the required libraries to run the GUI examples I noticed on the Python page that qt4 is no longer supported, so I only loaded qt5.

To make the camera-config-gui.py and camera-config-gui-oo.py examples to work, I changed the imports to the following:
`from PyQt5 import QtCore, QtWidgets`
`from PyQt5.QtCore import Qt`
...and changed all references of _QtGui_ to _QtWidgets_.

This seems to have done the trick.

**Comment by jim-easterbrook** [comment]
You're right, it's probably time to drop Qt4. I don't expect all the examples to work straight out of the box for all users, and it can be a bit of a guessing game knowing what packages are most widely installed.

**Comment by jim-easterbrook** [comment]
This is fixed in commit ebf766c.
