### ISSUE TITLE
gp_camera_capture_preview locks the mirror

### ISSUE THREAD

**Issue by dmitryelj** [jim-easterbrook/python-gphoto2#53]
Hi Jim,

Small question, maybe you know the answer.

I'm testing gp_camera_capture_preview to get the stream, it works fine, but even after camera.exit() mirror is staying locked in open position. Do you know good solution to fix that?

One hacky way, I've found, is to initialise the camera second time:
```
camera.exit(context)
time.sleep(0.5)
context = gp.Context()
camera = gp.Camera()
camera.init(context)
time.sleep(0.5)
camera.exit(context)
```

It releases the mirror, and user can use the camera further. Its definitely should be a better way? Even the "gphoto2 --capture-movie=100" command having the same 'bug'.

And a second question, btw - there is absolutely no way to change mjpeg preview image size?

Thanks a lot.

**Comment by jim-easterbrook** [comment]
I have no idea about either question. You might get an answer from the gphoto2 users mailing list, as someone there might have the same model of camera and might have tried something similar.

**Comment by dmitryelj** [comment]
Thanks, I'll ask there.
