### ISSUE TITLE
How to get camera object with a particular model name

### ISSUE THREAD

**Issue by rahulgautam** [jim-easterbrook/python-gphoto2#57]
For me, gphoto2 is not able to identify my camera until I pass the camera model as a parameter

```gphoto2 --camera "Canon EOS 1300D" --summary```

How can I pass camera model "Canon EOS 1300D" while getting context or camera object from gphoto2?

**Comment by jim-easterbrook** [comment]
Does the `choose-camera.py` example work for you? If not, you might have to look through the source of the gphoto command line program to see how it's using the `--camera` option.
