### ISSUE TITLE
Thread gp_camera_init

### ISSUE THREAD

**Issue by henrybetts** [jim-easterbrook/python-gphoto2#59]
Hi Jim,

Occasionally I have a situation where gp_camera_init takes a long time to return (sometimes 10+ seconds). At the moment this is blocking all other python threads.

Would it be ok to mark gp_camera_init as threaded? Happy to make a pull request.

Thanks,
Henry

**Comment by jim-easterbrook** [comment]
Good point, and one I should have picked up myself. No need for a PR, it's a trivial change I'll do in the next minute or two.
