### ISSUE TITLE
gp.use_python_logging with non-root logger 

### ISSUE THREAD

**Issue by MikeTough** [jim-easterbrook/python-gphoto2#60]
Hi Jim,

Firstly many, many thanks for your python bindings for gphoto. They have been working flawlessly for me so far. (gphoto2, on the other hand, is a bit of a handful - but I'm gradually getting the hang of it :) :) )

I have a query regarding your gp.use_python_logging function. With the exception of the information in your "ReadMe" file, I cannot find any description of the possible parameters for this function. (pydoc gphoto2 does not contain any info on this). Do you have a list of the possible parameters? (or is it limited to the mapping parameter?)

When redirecting the output of the DEBUG information from gphoto (as per the ReadMe example), the function appears to direct all output to the root logger. In my application the camera functions are only a small part of a larger whole and it would be convenient to send the log to a defined child logger of the root rather than directly to the root itself. Is this possible with the bindings as it stands?

Regards

Mike Tough

**Comment by jim-easterbrook** [comment]
The mapping is the only parameter to use_python_logging. The logging should be sent to a 'gphoto2' logger (see line 194 of the source file port_log.i).
https://github.com/jim-easterbrook/python-gphoto2/blob/master/src/gphoto2/port_log.i#L178

**Comment by jim-easterbrook** [comment]
The pydoc problem is to do with `use_python_logging` being written in Python (nearly all the other functions are written in SWIG generated C). pydoc uses `__all__` if it's defined, but it isn't for the Python part of the interface. When using `-builtin` there is a `__all__` for the C extension but not for the Python wrapper. I'm not sure I can safely add `use_python_logging` to it without breaking something else.

**Comment by MikeTough** [comment]
Hi Jim,

Many thanks for your rapid reply. This was just the info I was after :)
I've now got the logging just the way I want.

Best Regards

Mike
