### ISSUE TITLE
Can I use this to stream video?

### ISSUE THREAD

**Issue by sabetAI** [jim-easterbrook/python-gphoto2#61]
I'd like to use this library to stream video so I can integrate a Ricoh Theta V 360 camera with ROS. Currently getting the camera to take pictures is very slow, I was hoping there's a faster way if streaming is possible.

**Comment by jim-easterbrook** [comment]
This page is for reporting bugs in the python-gphoto2 interface to the libgphoto2 library. Questions about libgphoto2 should be asked on its mailing list: http://gphoto.org/mailinglists/

I think question 3.1.2 in the gphoto2 FAQ (http://gphoto.org/doc/manual/FAQ.html) answers your question. libgphoto2 "only works with still pictures".
