### ISSUE TITLE
Can't find "development headers" version of libgphoto2 

### ISSUE THREAD

**Issue by greiginsydney** [jim-easterbrook/python-gphoto2#62]
I appreciate this isn't a bug in python-gphoto2, but it's blocking me. Can anyone give me a nudge in the right direction?

I'm installing onto a Pi running raspbian 9 Stretch (and I've had everything working before on this release - just this time I'm trying to build onto a Zero).

 `sudo pip install -v libgphoto2` fails for me, as the two locations it's looking are dead:
`Could not fetch URL https://pypi.python.org/simple/libgphoto2/: 404 Client Error: Not Found for url` ...
`Could not fetch URL https://www.piwheels.org/simple/libgphoto2/: 404 Client Error: Not Found for url` ...

The handy script from here was my next attempt:
`https://github.com/gonzalo/gphoto2-updater` but despite it looking like it's gone OK, I can't find the examples anywhere and I don't have any confidence it's worked correctly.

Any ideas? Thanks.

**Comment by jim-easterbrook** [comment]
The command `sudo pip install -v libgphoto2` will attempt to install a Python package called `libgphoto2`, which does not exist. You need to use `apt-get` to install the `libgphoto2` library (dev headers version).

**Comment by greiginsydney** [comment]
Thanks for the quick response Jim. Any ideas what I'm still missing here? 

`pi@pzero:/ $ sudo apt-get install libgphoto2`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`E: Unable to locate package libgphoto2`
`pi@pzero:/ $`

**Comment by jim-easterbrook** [comment]
That's just the library, not its development headers. `apt-cache search libgphoto2` should show you what to install.

**Comment by greiginsydney** [comment]
Thanks Jim. Champion!! My Pi Zero is online!! I think my problem was just mixing up pip and apt-get.

For anyone following at home my fix was to:
`apt-cache search libgphoto2` which revealed I needed the below:
`sudo apt-get install libgphoto2-dev`
and for good measure I followed with:
`sudo pip install -v -U --force-reinstall gphoto2`
