### ISSUE TITLE
How to capture image quicker

### ISSUE THREAD

**Issue by gachiemchiep** [jim-easterbrook/python-gphoto2#63]
Hello @jim-easterbrook 

Thank you for your great work.

Do you know how to decrease the time which cost for capturing image ?

Currently my Nikon D5600 capture one image which has size 4000x3000 (h, w) in around 1.1 seconds. 
Is there any approach that help me reduce the capturing time in around 0.5 seconds.

```python
logger.info("Capture")
file_path = gp.check_result(gp.gp_camera_capture(camera, gp.GP_CAPTURE_IMAGE))

logger.info("Capture 1")
camera_file = gp.check_result(gp.gp_camera_file_get(
    camera, file_path.folder, file_path.name, gp.GP_FILE_TYPE_NORMAL))

logger.info("Capture 2")
file_data = gp.check_result(gp.gp_file_get_data_and_size(camera_file))

logger.info("Convert")
img_pil = Image.open(io.BytesIO(file_data))
img = np.asarray(img_pil)
cv2.imwrite("{}.png".format(idx), img)
imgs.append(img)
```

```python
[1537258708.4] [INFO] [    grab] START Grab
[1537258708.4] [INFO] [    grab] Capture
[1537258709.51] [INFO] [    grab] Capture 1
[1537258709.51] [INFO] [    grab] Capture 2
[1537258709.51] [INFO] [    grab] Convert
[1537258710.15] [INFO] [    grab] END Grab
```

Thank you for your kindness

**Comment by jim-easterbrook** [comment]
How does this compare with using the gphoto2 cli program? If it's similar, then the problem is in libgphoto2, not the Python interface.

**Comment by jim-easterbrook** [comment]
Slow capture is obviously a problem with libgphoto2 itself, not with the Python interface. I don't know much about how libgphoto2 works. As explained in the README, questions about gphoto2 should be asked on the gphoto2 mailing list, not reported as a python-gphoto2 issue.
