### ISSUE TITLE
ImportError: No module named gphoto2

### ISSUE THREAD

**Issue by maxholgasson** [jim-easterbrook/python-gphoto2#64]
Hi,

I try to run your example `import gphoto2 as gp
context = gp.gp_context_new()
error, camera = gp.gp_camera_new()
error = gp.gp_camera_init(camera, context)
error, text = gp.gp_camera_get_summary(camera, context)
print('Summary')
print('=======')
print(text.text)
error = gp.gp_camera_exit(camera, context)`

but get that error that the module gphoto2 is not found.

In the terminal "gphoto2 -L" or capture a photo works perfect however

**Comment by jim-easterbrook** [comment]
Have you installed the `python-gphoto2` package without any error message?
