### ISSUE TITLE
PIP install on Mac OS X

### ISSUE THREAD

**Issue by scoob-x13x** [jim-easterbrook/python-gphoto2#7]
Hi
i want to install it over PIP but i get an error

    ld: library not found for -lexif
    
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
    Command "/Library/Frameworks/Python.framework/Versions/3.4/bin/python3 -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-i1ba25_o/gphoto2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5bbvwecu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-i1ba25_o/gphoto2

**Comment by jim-easterbrook** [comment]
Does the output of the command ``pkg-config --libs-only-l libgphoto2`` include ``-lexif``? If so, this confirms that the libexif is required by any program that uses libgphoto2, so it should have been installed automatically when you installed libgphoto2. Try installing libexif directly before installing python-gphoto2.

**Comment by scoob-x13x** [comment]
Yes this is the output
-lgphoto2 -lm -lgphoto2_port -lm -lexif 
I installed libexif over Macport and its the same error

**Comment by jim-easterbrook** [comment]
Unfortunately I don't know much about MacOS X.
libexif is installed but the python-gphoto2 linking isn't finding it, suggesting it isn't in a "standard" location (if MacOS X has such a thing). On my Linux boxes it's in /usr/lib64/ so the link has no trouble finding it.
Does the output of ``pkg-config --libs-only-L libgphoto2`` show anything? (On my Linux boxes it's blank.)

**Comment by jim-easterbrook** [comment]
Are you able to download the tar.gz (or zip) file from PyPI and edit setup.py? If so, can you try changing the line
``libraries = list(map(lambda x: x.replace('-l', ''), gphoto2_libs))``
to
``libraries = ['gphoto2']``
before running ``python setup.py build`` and ``sudo python setup.py install``. If that works then it appears I needn't bother using ``pkg-config`` to get the list of libraries to link with.

**Comment by jim-easterbrook** [comment]
Can you try release 0.11.1 - I've added a 'library_dirs' parameter to the compilation that might help.

**Comment by scoob-x13x** [comment]
Thank you
Now it works
