### ISSUE TITLE
maintain in half press (to force autofocus) and take images

### ISSUE THREAD

**Issue by pdeman** [jim-easterbrook/python-gphoto2#74]
Hi,

I am trying to maintain the shutter opened and "autofocus working"
and then start some image aquisition in raw format.

I thought the eosremoterelease config allowed that.

I did 
```
gphoto2.gp_widget_set_value(configRemoteRelease,"Press Half")
gphoto2.gp_camera_set_config(camera,fullconfig).
```

but I don't here the shutter opening, neither the autofocus "running".
is there an other way to do that ?

**Comment by jim-easterbrook** [comment]
Not that I know of. This isn't really a good place to ask such questions. The gphoto2 mailing lists are more appropriate.

**Comment by pdeman** [comment]
ok thanks
