### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by colibrisson** [jim-easterbrook/python-gphoto2#77]
Hi,

When I run pip install gphoto2 I get the following error:

`Collecting gphoto2
  Using cached https://files.pythonhosted.org/packages/f2/55/dcd3834757c13fcdf7f611e67b6636b773754057202ce60a54e656528f92/gphoto2-1.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR: command "pkg-config --modversion libgphoto2" failed
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q16pg5xz/gphoto2/setup.py", line 38, in <module>
        cmd, stderr=FNULL, universal_newlines=True).split('.')
      File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['pkg-config', '--modversion', 'libgphoto2']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-q16pg5xz/gphoto2/`

I get the same error when I run the command with sudo. Libgphoto2 is installed and working. I don't have any issue when I install the Ubuntu maintained package.

**Comment by jim-easterbrook** [comment]
Try directly running the command `pkg-config --modversion libgphoto2`, i.e. the command that failed according to the error message. My guess is that you haven't installed the "development" version of libgphoto2 (i.e. its header files), but it's possible you don't have the `pkg-config` command.

**Comment by jim-easterbrook** [comment]
@colibrisson Did you get anywhere with this?
