### ISSUE TITLE
PIP install on OSX, 'error: too few arguments'

### ISSUE THREAD

**Issue by Nepomuk** [jim-easterbrook/python-gphoto2#8]
I wanted to install python-gphoto2 via pip on my laptop running OSX 10.10 Yosemite. Unfortunately, the installation procedure fails:

        src/swig-gp2.5/gphoto2_port_log_wrap.c:4120:57: error: too few arguments to function call, expected at least 4, have 3
    
          gp_log_data((char const *)arg1,(char const *)arg2,arg3);
          ~~~~~~~~~~~                                           ^
        
        /usr/local/Cellar/libgphoto2/2.5.7/include/gphoto2/gphoto2-port-log.h:88:1: note: 'gp_log_data' declared here
        
        void gp_log_data (const char *domain, const char *data, unsigned int size,
        
        ^
        
        1 error generated.
        
        error: command 'clang' failed with exit status 1

I have a recent installation of gphoto2:

        This version of gphoto2 is using the following software versions and options:
        gphoto2         2.5.6          clang, popt(m), no exif, no cdk, no aa, jpeg, readline
        libgphoto2      2.5.7          all camlibs, clang, ltdl, no EXIF
        libgphoto2_port 0.12.0         clang, ltdl, USB, serial without locking

Interestingly, when I clone the git repo and install this, the installation runs through and it seems fine. At least I get the examples to run. They are producing some errors, but I can see output from the camera.

        $ python camera-summary.py
        ERROR: gphoto2: (foreach_func [gphoto2-port-info-list.c:237]) Error during assembling of port list: 'Unspecified error' (-1).
        ERROR: gphoto2: (gp_port_usb_close [libusb.c:322]) Invalid parameters: 'port && port->pl->dh' is NULL/FALSE.
        ERROR: gphoto2: (ptp_list_folder_eos [library.c:6674]) storage 0xffffffff, but handle 0x00000000?
        Summary
        =======
        Manufacturer: Canon Inc.
        Model: Canon EOS 600D
          Version: 3-1.0.2
        […]

When I do the same with gphoto2 directly, these errors don't appear:

        $ gphoto2 --summary
        Camera summary:                                                                
        Manufacturer: Canon Inc.
        Model: Canon EOS 600D
          Version: 3-1.0.2

So right now I think I'm fine, but it seems strange why it doesn't work via pip.

**Comment by jim-easterbrook** [comment]
The reason it works when you install from git is that you are running SWIG to generate interfaces for the libgphoto2 header files on your machine. When installing with pip you download interfaces I built using SWIG on my Linux box. I had hoped they'd be compatible.
(The error messages from the example are typical of what I get. A lot of the libgphoto2 modules seem to report rather too much, and there's no way to tell errors from warnings in the Python interface.)
Can you find the libgphoto2 header files on your machine, zip/tar them and email them to me? I'd like to see where they differ from what I've got.

**Comment by jim-easterbrook** [comment]
Thanks for sending me the headers. I suspect the difference is libgphoto2 v2.5.7 (yours) vs 2.5.5 (mine) rather than a Mac vs Linux problem. The gp_log_data function signature has changed, acquiring a format string and variable arguments - not good news for a Python interface.
I don't think there's any need to call this function from within Python, so it might solve the problem if it's added to the 'ignore' list when building the interfaces.

**Comment by Nepomuk** [comment]
Sounds good. If I should try again with pip, let me know.

**Comment by jim-easterbrook** [comment]
I'd like to try and sort out bug #7 before the next release, so give me a day or two.
I'd also like to work out what's going on with the excessive verbosity.

**Comment by Nepomuk** [comment]
Ah, don't worry. It's working for me now, so at this point it's just helping you to solve the installation bug.

**Comment by jim-easterbrook** [comment]
Release 0.11.1 should have fixed this bug.

**Comment by Nepomuk** [comment]
$ pip install gphoto2
        […]
        Successfully installed gphoto2-0.11.1

It works, thank you!
