### ISSUE TITLE
Keep file on card while wait for event

### ISSUE THREAD

**Issue by robertiii** [jim-easterbrook/python-gphoto2#81]
How can I have the file save to the card as well as save to the computer?

**Comment by jim-easterbrook** [comment]
Set your camera to record to memory card, I assume. This sounds like a question about libgphoto2 itself rather than the Python interface. I'm not an expert on libgphoto2.

**Comment by robertiii** [comment]
So I’ll be honest I’m quite ignorant of how any of it works! Lol I have been copying code and modifying slightly.

**Comment by robertiii** [comment]
I think I saw somewhere there is a --keep tag?

**Comment by jim-easterbrook** [comment]
It takes a lot of experimenting to find what works or not with any particular camera. Any `--keep` option would be part of the `gphoto2` CLI program. You can look at its source code to find out how it uses the `libgphoto2` library.

**Comment by robertiii** [comment]
Pardon my ignorance. I’m not understanding. So sorry
