### ISSUE TITLE
Capturing and deleting file on camera

### ISSUE THREAD

**Issue by sinhau** [jim-easterbrook/python-gphoto2#83]
Is there a Python equivalent to `gphoto2 --capture-image-and-download`?  My goal is to the capture the image from a camera but only save the image on my PC and **not** on the camera itself.  Currently, I am using `gp_camera_capture` followed by `gp_camera_file_get` and `gp_file_save` to capture and save the image on the PC, but a copy of the image is also locally stored on the camera itself.  I'm using a RICOH Theta S, so there's no way for me to remove the internal memory card.  How can I delete the local image on the camera or have it not save locally in the first place? 

Thanks!

**Comment by jim-easterbrook** [comment]
Can you set your camera to record to memory only? I can do this on my Canons but I've no idea what the interface to your Ricoh is like. Try the config gui example to see what settings are available. The set-capture-target example shows how to set the capture target (on my Canons). The time-lapse example shows its use in a more complete program.
