### ISSUE TITLE
LivePreview

### ISSUE THREAD

**Issue by scoob-x13x** [jim-easterbrook/python-gphoto2#9]
Hi Jim,

i have a Question. Is there a LivePreview like in piggyphoto?

Best regards
ScooB

**Comment by jim-easterbrook** [comment]
I assume piggyphoto is calling the gp_camera_capture_preview() function to get a preview. If so, you can do that with python-gphoto2, then use gp_file_get_data_and_size() on the returned file to get the image data, then display it in a preview window of your choice (Qt, Tk, OpenGL, etc.).

**Comment by scoob-x13x** [comment]
Yes but when i Calling gp_camera_capture_preview() then i always take a picture and the mirror is always going up and down. In piggyphoto there is an attribute called _leave_locked and when its True the mirror is flipped up and is locked. Then i can be is a loop and can display the image

**Comment by jim-easterbrook** [comment]
I assume that's a camera configuration setting (gp_camera_get_config & gp_camera_set_config). All I know about libgphoto2 is what's in its documentation, and python-gphoto2 just provides a Python interface to that API.

**Comment by scoob-x13x** [comment]
In libgphoto2 gp_camera_capture_preview() takes 3 parameters in python-gphoto2 it only takes 2 parameters.
The parameters are
camera -	a Camera
file	- a CameraFile
context -	a GPContext

The file parameter is missing is that a mistake in python-gphoto2?

**Comment by jim-easterbrook** [comment]
No, it is not a mistake. The CameraFile is an output parameter that is allocated and returned by the function, as described in the README.

**Comment by hollesse** [comment]
@jim-easterbrook is it possible to get like a video stream as a live preview?

**Comment by jim-easterbrook** [comment]
Not with libgphoto2. I'd post a link to the libgphoto2 documentation but the web site is currently unavailable. I'm not aware of any libgphoto2 function that can stream anything.

**Comment by bitcraft** [comment]
Downloading preview images is pretty fast. I can sustain about 20 FPS with
jpegs on “medium”. Not as good as video, but works good enough for my
purposes.
