### ISSUE TITLE
Bulb exposure

### ISSUE THREAD

**Issue by timotoots** [jim-easterbrook/python-gphoto2#90]
Hey, I am trying to implement bulb exposure time. The command line utility uses config values for that (--set-config bulb=1 --wait-event=30s --set-config bulb=0 --wait-event-and-download=2s)

How to use camera.capture(gp.GP_CAPTURE_IMAGE) with bulb exposure? And how to set the actual exposure time?

**Comment by jim-easterbrook** [comment]
Does the config gui show a 'bulb' item? If so then perhaps you can set the config item, then wait 30 seconds, then set it back to zero. Fetching all events from the camera should then tell you the file name of the captured image.
