### ISSUE TITLE
Writing exif data to camera

### ISSUE THREAD

**Issue by dlwalter** [jim-easterbrook/python-gphoto2#95]
Is there a way to write exif data to the files on the camera?  

I'm looking to modify the exif gps location data either before the image is taken or after it is saved onto the SD Card, without downloading to the host computer.

**Comment by jim-easterbrook** [comment]
The libgphoto2 API documentation is here: http://www.gphoto.org/doc/api/

I think the only way to do what you want is to copy the image data to the computer with `gp_camera_file_get`, modify its Exif data (in memory), then copy it back with `gp_camera_folder_put_file`.
