### ISSUE TITLE
Trigger capture very slow on Canon SX740HS - approx 1 per seconds.

### ISSUE THREAD

**Issue by dlwalter** [jim-easterbrook/python-gphoto2#97]
This page is for reporting problems with the Python interface to libgphoto2. If your question is about using libgphoto2 you should ask on the [gphoto2 mailing list](http://gphoto.org/mailinglists/).

**Your system**
Python 3.6.1, Canon Powershot SX740HS

What version of libgphoto2 have you installed?
2.5.12

How have you installed (or attempted to install) python-gphoto2?

**Your problem**
I have a basic loop calling camera.capture as fast as possible.  I can only trigger captures at about 1 every 2 seconds.  Is there a way to increase the rate of single capture triggers?  I am hoping to hit 3 per second.  I thought it would be the sd card write throttling me, but I get the same time when capturetarget=0 or 1.

**Comment by jim-easterbrook** [comment]
How fast can the gphoto2 cli program do it?

**Comment by dlwalter** [comment]
Unfortunately the cli does a whole lens retraction/extension between each trigger-capture, so I can't get a good timing.

I was able to speed up to about 2/s by setting the camera focusmode to 'Manual'.
